version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    command: ["npm","run","dev","--","--host"]
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
